export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_REVOKED: "AUTH_SESSION_REVOKED",
  AUTH_MFA_REQUIRED: "AUTH_MFA_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  ORDER_STATE_CONFLICT: "ORDER_STATE_CONFLICT",
  ASSIGNMENT_CONFLICT: "ASSIGNMENT_CONFLICT",
  ASSIGNMENT_OFFER_EXPIRED: "ASSIGNMENT_OFFER_EXPIRED",
  RESOURCE_VERSION_MISMATCH: "RESOURCE_VERSION_MISMATCH",
  PRECONDITION_REQUIRED: "PRECONDITION_REQUIRED",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  PROOF_REQUIRED: "PROOF_REQUIRED",
  PROOF_NOT_READY: "PROOF_NOT_READY",
  RATE_LIMITED: "RATE_LIMITED",
  DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];